version: '3.3'
services:
  frps:
    restart: always
    network_mode: host
    volumes:
      - './frps.toml:/etc/frp/frps.toml'
    container_name: frps
    image: snowdreamtech/frps
    command: "/bin/frps -c /etc/frp/frps.toml"
